### ISSUE TITLE
Tighter version constraint on exported package

### ISSUE THREAD

**Issue by nex3** [groboclown/builder.dart#33]
Per [the new exported dependency guidelines](https://groups.google.com/a/dartlang.org/forum/#!topic/misc/6PjWjxveQjQ), the dependency constraint for `unittest` should be narrowed to `>=0.11.3 <0.11.4`.

Also, since code in `lib/` uses `unittest`, it shouldn't be a dev dependency.

**Comment by groboclown** [comment]
Added the fix to the master branch.
